import { Employee, Location, CheckInOutRecord } from '@/types';

// Mock LSC STAFF Employees
export const mockEmployees: Employee[] = [
  {
    id: 'STAFF001',
    firstName: 'John',
    lastName: 'Smith',
    name: 'John Smith',
    email: 'john.smith@company.com',
    mobilePhoneNo: '+1-555-0101',
    jobTitle: 'Sales Associate',
    status: 'Active',
    retailStaffId: 'RS001',
    retailUserId: 'john.smith',
    employeeNo: 'EMP001',
    workRegion: 'WEST',
    workLocation: 'LOC001',
    timeEntryId: 'TE001',
    workRole: 'SALES',
  },
  {
    id: 'STAFF002',
    firstName: 'Sarah',
    lastName: 'Johnson',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    mobilePhoneNo: '+1-555-0102',
    jobTitle: 'Sales Associate',
    status: 'Active',
    retailStaffId: 'RS002',
    retailUserId: 'sarah.johnson',
    employeeNo: 'EMP002',
    workRegion: 'WEST',
    workLocation: 'LOC001',
    timeEntryId: 'TE002',
    workRole: 'SALES',
  },
  {
    id: 'STAFF003',
    firstName: 'Michael',
    lastName: 'Brown',
    name: 'Michael Brown',
    email: 'michael.brown@company.com',
    mobilePhoneNo: '+1-555-0103',
    jobTitle: 'Warehouse Staff',
    status: 'Active',
    retailStaffId: 'RS003',
    retailUserId: 'michael.brown',
    employeeNo: 'EMP003',
    workRegion: 'EAST',
    workLocation: 'LOC004',
    timeEntryId: 'TE003',
    workRole: 'WAREHOUSE',
  },
  {
    id: 'STAFF004',
    firstName: 'Emily',
    lastName: 'Davis',
    name: 'Emily Davis',
    email: 'emily.davis@company.com',
    mobilePhoneNo: '+1-555-0104',
    jobTitle: 'Customer Service',
    status: 'Active',
    retailStaffId: 'RS004',
    retailUserId: 'emily.davis',
    employeeNo: 'EMP004',
    workRegion: 'WEST',
    workLocation: 'LOC002',
    timeEntryId: 'TE004',
    workRole: 'SERVICE',
  },
  {
    id: 'STAFF005',
    firstName: 'Robert',
    lastName: 'Wilson',
    name: 'Robert Wilson',
    email: 'robert.wilson@company.com',
    mobilePhoneNo: '+1-555-0105',
    jobTitle: 'Store Manager',
    status: 'Active',
    retailStaffId: 'RS005',
    retailUserId: 'robert.wilson',
    employeeNo: 'EMP005',
    workRegion: 'WEST',
    workLocation: 'LOC001',
    timeEntryId: 'TE005',
    workRole: 'MANAGER',
  },
  {
    id: 'STAFF006',
    firstName: 'Jennifer',
    lastName: 'Martinez',
    name: 'Jennifer Martinez',
    email: 'jennifer.martinez@company.com',
    mobilePhoneNo: '+1-555-0106',
    jobTitle: 'Area Manager',
    status: 'Active',
    retailStaffId: 'RS006',
    retailUserId: 'jennifer.martinez',
    employeeNo: 'EMP006',
    workRegion: 'WEST',
    workLocation: 'LOC001',
    timeEntryId: 'TE006',
    workRole: 'MANAGER',
  },
];

// Mock LSC Work Locations
export const mockLocations: Location[] = [
  {
    id: 'LOC001',
    name: 'Headquarters Store',
    workRegion: 'WEST',
    storeNo: 'S001',
    responsiblePerson: 'STAFF005',
    status: 'Active',
    globalDimension1Code: 'RETAIL',
    globalDimension2Code: 'WEST',
  },
  {
    id: 'LOC002',
    name: 'Downtown Store',
    workRegion: 'WEST',
    storeNo: 'S002',
    responsiblePerson: 'STAFF005',
    status: 'Active',
    globalDimension1Code: 'RETAIL',
    globalDimension2Code: 'WEST',
  },
  {
    id: 'LOC003',
    name: 'Eastside Mall Store',
    workRegion: 'EAST',
    storeNo: 'S003',
    responsiblePerson: 'STAFF006',
    status: 'Active',
    globalDimension1Code: 'RETAIL',
    globalDimension2Code: 'EAST',
  },
  {
    id: 'LOC004',
    name: 'South Distribution Center',
    workRegion: 'SOUTH',
    storeNo: null,
    responsiblePerson: 'STAFF006',
    status: 'Active',
    globalDimension1Code: 'WAREHOUSE',
    globalDimension2Code: 'SOUTH',
  },
  {
    id: 'LOC005',
    name: 'North Service Hub',
    workRegion: 'NORTH',
    storeNo: 'S005',
    responsiblePerson: 'STAFF006',
    status: 'Active',
    globalDimension1Code: 'SERVICE',
    globalDimension2Code: 'NORTH',
  },
];

// Helper to create dates relative to now
const hoursAgo = (hours: number): Date => {
  const date = new Date();
  date.setHours(date.getHours() - hours);
  return date;
};

const daysAgo = (days: number, hour: number = 9): Date => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  date.setHours(hour, 0, 0, 0);
  return date;
};

// Helper to format time as HH:MM:SS
const formatTime = (date: Date): string => {
  return date.toTimeString().split(' ')[0];
};

// Mock LSC Time Entry Registration records
export const mockCheckInOutRecords: CheckInOutRecord[] = [
  // Current open check-in for STAFF001
  {
    id: 1,
    employeeId: 'STAFF001',
    locationId: 'LOC001',
    workRoleCode: 'SALES',
    systemDateEntry: hoursAgo(2),
    systemTimeEntry: formatTime(hoursAgo(2)),
    systemDateExit: null,
    systemTimeExit: null,
    userDateEntry: null,
    userTimeEntry: null,
    userDateExit: null,
    userTimeExit: null,
    noOfHours: null,
    status: 'Open',
    entryStatus: 'OK',
    leavingStatus: null,
    entryMethod: 'Automatic',
    entryEmployeeComment: '',
    originLogon: 'PowerApp',
    checkInTime: hoursAgo(2),
    checkOutTime: null,
    durationMinutes: null,
  },
  // Yesterday's record for STAFF001
  {
    id: 2,
    employeeId: 'STAFF001',
    locationId: 'LOC001',
    workRoleCode: 'SALES',
    systemDateEntry: daysAgo(1, 9),
    systemTimeEntry: '09:00:00',
    systemDateExit: daysAgo(1, 17),
    systemTimeExit: '17:00:00',
    userDateEntry: null,
    userTimeEntry: null,
    userDateExit: null,
    userTimeExit: null,
    noOfHours: 8.0,
    status: 'Closed',
    entryStatus: 'OK',
    leavingStatus: 'OK',
    entryMethod: 'Automatic',
    entryEmployeeComment: 'Regular workday',
    originLogon: 'PowerApp',
    checkInTime: daysAgo(1, 9),
    checkOutTime: daysAgo(1, 17),
    durationMinutes: 480,
  },
  // Two days ago - different location
  {
    id: 3,
    employeeId: 'STAFF001',
    locationId: 'LOC003',
    workRoleCode: 'SALES',
    systemDateEntry: daysAgo(2, 10),
    systemTimeEntry: '10:00:00',
    systemDateExit: daysAgo(2, 16),
    systemTimeExit: '16:00:00',
    userDateEntry: null,
    userTimeEntry: null,
    userDateExit: null,
    userTimeExit: null,
    noOfHours: 6.0,
    status: 'Closed',
    entryStatus: 'Late',
    leavingStatus: 'Early',
    entryMethod: 'Automatic',
    entryEmployeeComment: 'Client meeting at Eastside Mall',
    originLogon: 'PowerApp',
    checkInTime: daysAgo(2, 10),
    checkOutTime: daysAgo(2, 16),
    durationMinutes: 360,
  },
  // Three days ago
  {
    id: 4,
    employeeId: 'STAFF001',
    locationId: 'LOC001',
    workRoleCode: 'SALES',
    systemDateEntry: daysAgo(3, 8),
    systemTimeEntry: '08:00:00',
    systemDateExit: daysAgo(3, 18),
    systemTimeExit: '18:00:00',
    userDateEntry: null,
    userTimeEntry: null,
    userDateExit: null,
    userTimeExit: null,
    noOfHours: 10.0,
    status: 'Processed',
    entryStatus: 'Early',
    leavingStatus: 'Late',
    entryMethod: 'Automatic',
    entryEmployeeComment: '',
    originLogon: 'PowerApp',
    checkInTime: daysAgo(3, 8),
    checkOutTime: daysAgo(3, 18),
    durationMinutes: 600,
  },
  // Four days ago
  {
    id: 5,
    employeeId: 'STAFF001',
    locationId: 'LOC002',
    workRoleCode: 'SALES',
    systemDateEntry: daysAgo(4, 9),
    systemTimeEntry: '09:00:00',
    systemDateExit: daysAgo(4, 17),
    systemTimeExit: '17:00:00',
    userDateEntry: null,
    userTimeEntry: null,
    userDateExit: null,
    userTimeExit: null,
    noOfHours: 8.0,
    status: 'Processed',
    entryStatus: 'OK',
    leavingStatus: 'OK',
    entryMethod: 'Automatic',
    entryEmployeeComment: 'Downtown store training',
    originLogon: 'PowerApp',
    checkInTime: daysAgo(4, 9),
    checkOutTime: daysAgo(4, 17),
    durationMinutes: 480,
  },
  // Records for other employees
  {
    id: 6,
    employeeId: 'STAFF002',
    locationId: 'LOC001',
    workRoleCode: 'SALES',
    systemDateEntry: hoursAgo(3),
    systemTimeEntry: formatTime(hoursAgo(3)),
    systemDateExit: null,
    systemTimeExit: null,
    userDateEntry: null,
    userTimeEntry: null,
    userDateExit: null,
    userTimeExit: null,
    noOfHours: null,
    status: 'Open',
    entryStatus: 'OK',
    leavingStatus: null,
    entryMethod: 'Automatic',
    entryEmployeeComment: '',
    originLogon: 'PowerApp',
    checkInTime: hoursAgo(3),
    checkOutTime: null,
    durationMinutes: null,
  },
  {
    id: 7,
    employeeId: 'STAFF003',
    locationId: 'LOC004',
    workRoleCode: 'WAREHOUSE',
    systemDateEntry: hoursAgo(4),
    systemTimeEntry: formatTime(hoursAgo(4)),
    systemDateExit: null,
    systemTimeExit: null,
    userDateEntry: null,
    userTimeEntry: null,
    userDateExit: null,
    userTimeExit: null,
    noOfHours: null,
    status: 'Open',
    entryStatus: 'OK',
    leavingStatus: null,
    entryMethod: 'Automatic',
    entryEmployeeComment: 'Warehouse shift',
    originLogon: 'PowerApp',
    checkInTime: hoursAgo(4),
    checkOutTime: null,
    durationMinutes: null,
  },
];

// Current logged-in user (for development)
export const currentUserId = 'STAFF001';
